services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

  backend:
    build:
      context: ./expedition
    container_name: gradle-backend
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: