name: Run Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Print all environment variables
        run: env

      - name: Wait for PostgreSQL to be healthy
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U admin && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL did not become healthy in time" && exit 1

      - name: Check PostgreSQL Connection
        run: |
          PGPASSWORD=admin psql -h localhost -U admin -d db -c 'SELECT datname FROM pg_database;'

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: admin
        working-directory: ./expedition
        run: |
          echo "Running tests with environment variables:"
          env | grep SPRING_
          ./gradlew test --info

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test